[2025-05-12T21:55:44.692+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_dag.track_processed_data manual__2025-05-12T16:55:09.417454+00:00 [queued]>
[2025-05-12T21:55:44.698+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_dag.track_processed_data manual__2025-05-12T16:55:09.417454+00:00 [queued]>
[2025-05-12T21:55:44.698+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-12T21:55:44.818+0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): track_processed_data> on 2025-05-12 16:55:09.417454+00:00
[2025-05-12T21:55:44.825+0500] {standard_task_runner.py:57} INFO - Started process 64974 to run task
[2025-05-12T21:55:44.828+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_dag', 'track_processed_data', 'manual__2025-05-12T16:55:09.417454+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/mlflow.py', '--cfg-path', '/tmp/tmplac9xctf']
[2025-05-12T21:55:44.828+0500] {standard_task_runner.py:85} INFO - Job 32: Subtask track_processed_data
[2025-05-12T21:55:44.955+0500] {task_command.py:416} INFO - Running <TaskInstance: data_pipeline_dag.track_processed_data manual__2025-05-12T16:55:09.417454+00:00 [running]> on host maemoon-Inspiron-15-3567
[2025-05-12T21:55:45.179+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_dag' AIRFLOW_CTX_TASK_ID='track_processed_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T16:55:09.417454+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T16:55:09.417454+00:00'
[2025-05-12T21:55:46.550+0500] {logging_mixin.py:151} INFO - Processed data tracked with DVC
[2025-05-12T21:55:46.813+0500] {logging_mixin.py:151} INFO - Processed data tracked with MLflow
[2025-05-12T21:55:46.839+0500] {logging_mixin.py:151} INFO - üèÉ View run data_tracking at: http://localhost:5000/#/experiments/0/runs/a712806f85be4cd1a100af49f8e50561
[2025-05-12T21:55:46.840+0500] {logging_mixin.py:151} INFO - üß™ View experiment at: http://localhost:5000/#/experiments/0
[2025-05-12T21:55:47.050+0500] {python.py:194} INFO - Done. Returned value was: None
[2025-05-12T21:55:47.388+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_pipeline_dag, task_id=track_processed_data, execution_date=20250512T165509, start_date=20250512T165544, end_date=20250512T165547
[2025-05-12T21:55:47.572+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-12T21:55:47.595+0500] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
