[2025-05-12T21:24:20.806+0500] {processor.py:157} INFO - Started process (PID=56316) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:24:20.807+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:24:20.807+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:24:20.807+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:24:20.810+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:24:20.809+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:24:20.810+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:24:20.810+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:24:20.810+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:24:20.821+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-05-12T21:30:25.928+0500] {processor.py:157} INFO - Started process (PID=57965) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:30:25.930+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:30:25.930+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:30:25.930+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:30:25.933+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:30:25.932+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:30:25.933+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:30:25.933+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:30:25.933+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:30:25.944+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-12T21:31:51.030+0500] {processor.py:157} INFO - Started process (PID=58575) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:31:51.031+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:31:51.032+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:31:51.032+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:31:51.035+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:31:51.034+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:31:51.035+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:31:51.035+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:31:51.035+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:31:51.044+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-12T21:33:13.330+0500] {processor.py:157} INFO - Started process (PID=59264) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:33:13.339+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:33:13.340+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:33:13.340+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:33:13.343+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:33:13.342+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:33:13.343+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:33:13.343+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:33:13.343+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:33:13.353+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-05-12T21:34:08.496+0500] {processor.py:157} INFO - Started process (PID=59410) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:34:08.514+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:34:08.515+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:34:08.515+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:34:08.518+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:34:08.517+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:34:08.518+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:34:08.518+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:34:08.518+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:34:08.527+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-05-12T21:35:01.321+0500] {processor.py:157} INFO - Started process (PID=59523) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:35:01.363+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:35:01.364+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:35:01.364+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:35:01.367+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:35:01.366+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:35:01.367+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:35:01.367+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:35:01.367+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:35:01.375+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2025-05-12T21:35:50.514+0500] {processor.py:157} INFO - Started process (PID=59764) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:35:50.516+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:35:50.519+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:35:50.519+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:35:50.526+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:35:50.525+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:35:50.526+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:35:50.526+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:35:50.526+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:35:50.546+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-05-12T21:52:45.784+0500] {processor.py:157} INFO - Started process (PID=63899) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:52:45.813+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:52:45.814+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:52:45.814+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:52:45.818+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:52:45.817+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:52:45.818+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:52:45.818+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:52:45.818+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:52:45.829+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-05-12T21:53:46.822+0500] {processor.py:157} INFO - Started process (PID=64123) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:53:46.832+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:53:46.833+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:53:46.832+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:53:46.836+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:53:46.836+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:53:46.837+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:53:46.836+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:53:46.837+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:53:46.845+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-05-12T21:54:49.961+0500] {processor.py:157} INFO - Started process (PID=64429) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:54:50.000+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:54:50.002+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:54:50.001+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:54:50.005+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:54:50.004+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:54:50.005+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:54:50.005+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:54:50.005+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:54:50.447+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.489 seconds
[2025-05-12T21:56:21.998+0500] {processor.py:157} INFO - Started process (PID=65255) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:56:21.999+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:56:22.000+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:56:22.000+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:56:22.003+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:56:22.002+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:56:22.003+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:56:22.003+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:56:22.004+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:56:22.014+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-05-12T21:57:13.715+0500] {processor.py:157} INFO - Started process (PID=65368) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:57:13.717+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:57:13.717+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:57:13.717+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:57:13.720+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:57:13.719+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:57:13.720+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:57:13.720+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:57:13.720+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:57:13.728+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-12T21:58:02.150+0500] {processor.py:157} INFO - Started process (PID=65465) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:58:02.151+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:58:02.152+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:58:02.152+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:58:02.158+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:58:02.157+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:58:02.159+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:58:02.159+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:58:02.159+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:58:02.169+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-05-12T21:58:57.458+0500] {processor.py:157} INFO - Started process (PID=65700) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:58:57.460+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:58:57.461+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:58:57.460+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:58:57.464+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:58:57.464+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:58:57.465+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:58:57.465+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:58:57.465+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:58:57.477+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-05-12T21:59:54.134+0500] {processor.py:157} INFO - Started process (PID=65805) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:59:54.135+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T21:59:54.135+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:59:54.135+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:59:54.138+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:59:54.138+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T21:59:54.138+0500] {logging_mixin.py:151} INFO - [2025-05-12T21:59:54.138+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T21:59:54.138+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T21:59:54.147+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-12T22:01:08.010+0500] {processor.py:157} INFO - Started process (PID=66163) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:01:08.011+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:01:08.012+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:01:08.011+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:01:08.017+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:01:08.016+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:01:08.017+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:01:08.017+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:01:08.017+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:01:08.027+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-05-12T22:03:11.723+0500] {processor.py:157} INFO - Started process (PID=67165) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:03:11.724+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:03:11.725+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:03:11.724+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:03:11.727+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:03:11.727+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:03:11.728+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:03:11.727+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:03:11.728+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:03:11.738+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-12T22:04:19.347+0500] {processor.py:157} INFO - Started process (PID=67427) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:04:19.348+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:04:19.349+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:04:19.349+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:04:19.352+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:04:19.351+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:04:19.352+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:04:19.352+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:04:19.352+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:04:19.360+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-05-12T22:05:12.632+0500] {processor.py:157} INFO - Started process (PID=67554) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:05:12.643+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:05:12.643+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:05:12.643+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:05:12.646+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:05:12.646+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:05:12.646+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:05:12.646+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:05:12.647+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:05:12.656+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-05-12T22:06:04.333+0500] {processor.py:157} INFO - Started process (PID=67691) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:06:04.351+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:06:04.352+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:06:04.352+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:06:04.355+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:06:04.354+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:06:04.355+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:06:04.355+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:06:04.355+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:06:04.363+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-05-12T22:06:52.851+0500] {processor.py:157} INFO - Started process (PID=67828) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:06:52.852+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:06:52.852+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:06:52.852+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:06:52.855+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:06:52.855+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:06:52.855+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:06:52.855+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:06:52.856+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:06:52.864+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-05-12T22:07:44.797+0500] {processor.py:157} INFO - Started process (PID=67962) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:07:44.798+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:07:44.798+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:07:44.798+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:07:44.802+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:07:44.801+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:07:44.802+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:07:44.802+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:07:44.802+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:07:44.817+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-05-12T22:08:39.489+0500] {processor.py:157} INFO - Started process (PID=68073) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:08:39.490+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:08:39.491+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:08:39.490+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:08:39.494+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:08:39.493+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:08:39.494+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:08:39.494+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:08:39.494+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:08:39.502+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-12T22:09:27.678+0500] {processor.py:157} INFO - Started process (PID=68175) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:09:27.679+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:09:27.679+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:09:27.679+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:09:27.682+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:09:27.682+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:09:27.682+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:09:27.682+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:09:27.682+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:09:27.691+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-05-12T22:10:20.399+0500] {processor.py:157} INFO - Started process (PID=68296) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:10:20.400+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:10:20.401+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:10:20.400+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:10:20.403+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:10:20.403+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:10:20.404+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:10:20.403+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:10:20.404+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:10:20.412+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-05-12T22:11:15.208+0500] {processor.py:157} INFO - Started process (PID=68614) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:11:15.209+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:11:15.210+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:11:15.209+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:11:15.212+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:11:15.212+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:11:15.213+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:11:15.213+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:11:15.213+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:11:15.221+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-05-12T22:12:04.568+0500] {processor.py:157} INFO - Started process (PID=68715) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:12:04.569+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:12:04.570+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:12:04.569+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:12:04.572+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:12:04.572+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:12:04.573+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:12:04.573+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:12:04.573+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:12:04.581+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-05-12T22:12:54.042+0500] {processor.py:157} INFO - Started process (PID=68810) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:12:54.092+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:12:54.093+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:12:54.093+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:12:54.097+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:12:54.096+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:12:54.097+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:12:54.097+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:12:54.098+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:12:54.108+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-05-12T22:13:44.489+0500] {processor.py:157} INFO - Started process (PID=68884) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:13:44.531+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:13:44.531+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:13:44.531+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:13:44.534+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:13:44.534+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:13:44.535+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:13:44.535+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:13:44.535+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:13:44.544+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2025-05-12T22:14:57.313+0500] {processor.py:157} INFO - Started process (PID=69006) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:14:57.327+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:14:57.327+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:14:57.327+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:14:57.330+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:14:57.330+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:14:57.331+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:14:57.330+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:14:57.331+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:14:57.341+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-05-12T22:15:50.432+0500] {processor.py:157} INFO - Started process (PID=69082) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:15:50.435+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:15:50.436+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:15:50.435+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:15:50.438+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:15:50.438+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:15:50.439+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:15:50.439+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:15:50.439+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:15:50.448+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-12T22:16:44.161+0500] {processor.py:157} INFO - Started process (PID=69222) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:16:44.162+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:16:44.163+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:16:44.163+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:16:44.166+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:16:44.165+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:16:44.166+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:16:44.166+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:16:44.166+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:16:44.174+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-05-12T22:17:37.799+0500] {processor.py:157} INFO - Started process (PID=69388) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:17:37.800+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:17:37.801+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:17:37.801+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:17:37.804+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:17:37.804+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:17:37.805+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:17:37.805+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:17:37.805+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:17:37.815+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-05-12T22:18:30.677+0500] {processor.py:157} INFO - Started process (PID=69539) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:18:30.680+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:18:30.681+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:18:30.681+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:18:30.684+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:18:30.684+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:18:30.685+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:18:30.684+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:18:30.685+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:18:30.697+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-05-12T22:19:23.874+0500] {processor.py:157} INFO - Started process (PID=69628) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:19:23.875+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:19:23.876+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:19:23.875+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:19:23.880+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:19:23.879+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:19:23.880+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:19:23.880+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:19:23.880+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:19:23.891+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-05-12T22:20:18.399+0500] {processor.py:157} INFO - Started process (PID=69729) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:20:18.415+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:20:18.416+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:20:18.416+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:20:18.419+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:20:18.418+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:20:18.419+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:20:18.419+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:20:18.419+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:20:18.427+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-05-12T22:21:13.143+0500] {processor.py:157} INFO - Started process (PID=69964) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:21:13.157+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:21:13.158+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:21:13.157+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:21:13.160+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:21:13.160+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:21:13.161+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:21:13.161+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:21:13.161+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:21:13.170+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-05-12T22:22:08.486+0500] {processor.py:157} INFO - Started process (PID=70137) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:22:08.509+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:22:08.510+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:22:08.509+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:22:08.513+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:22:08.512+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:22:08.513+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:22:08.513+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:22:08.514+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:22:08.522+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-05-12T22:23:01.440+0500] {processor.py:157} INFO - Started process (PID=70229) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:23:01.451+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:23:01.453+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:23:01.452+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:23:01.457+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:23:01.456+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:23:01.458+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:23:01.458+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:23:01.458+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:23:01.472+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-05-12T22:23:55.866+0500] {processor.py:157} INFO - Started process (PID=70363) to work on /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:23:55.882+0500] {processor.py:829} INFO - Processing file /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-05-12T22:23:55.883+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:23:55.883+0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:23:55.887+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:23:55.886+0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-05-12T22:23:55.887+0500] {logging_mixin.py:151} INFO - [2025-05-12T22:23:55.887+0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-05-12T22:23:55.887+0500] {processor.py:841} WARNING - No viable dags retrieved from /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-05-12T22:23:55.895+0500] {processor.py:179} INFO - Processing /home/maemoon/Documents/MLOPS_Project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
